services:
  db:
    build:
      context: ./src/backend
      dockerfile: mongo.Dockerfile
    container_name: project-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - backend-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: project-backend
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@db:27017/nosql_db
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network

  frontend:
    build: ./src/frontend
    container_name: project-frontend
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
    networks:
      - frontend-network

  seed:
    build:
      context: ./src/backend
      dockerfile: seed.Dockerfile
    container_name: project-seed
    depends_on:
      - backend
    environment:
      WAIT_BACKEND: "1"
      BASE_URL: "http://backend:8080/v1"
    volumes:
      - seed_done:/seed_done
    networks:
      - backend-network
    restart: "no"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        if [ -f /seed_done/.done ]; then
          echo "Seed уже выполнен, пропуск"
          exit 0
        fi
        cd /seed && ./seed-data.sh "http://backend:8080/v1" && touch /seed_done/.done
        echo "Seed завершён"

networks:
  backend-network:
    driver: bridge
    internal: true
  frontend-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  seed_done:
    driver: local