/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (get JWT) */
        post: operations["v1AuthLoginPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create university */
        post: operations["v1UniversityCreatePost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search universities */
        get: operations["v1UniversitiesSearchGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete university by id */
        delete: operations["v1UniversityByIdDelete"];
        options?: never;
        head?: never;
        /** Update university by id */
        patch: operations["v1UniversityByIdPatch"];
        trace?: never;
    };
    "/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List actors with filters */
        get: operations["v1ActorsGet"];
        put?: never;
        /** Create actor */
        post: operations["v1ActorCreatePost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get actor by id */
        get: operations["v1ActorByIdGet"];
        put?: never;
        post?: never;
        /** Delete actor profile */
        delete: operations["v1ActorByIdDelete"];
        options?: never;
        head?: never;
        /** Partially update actor */
        patch: operations["v1ActorByIdPatch"];
        trace?: never;
    };
    "/actors/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload actor media (photo or video to GridFS) */
        post: operations["v1ActorMediaUploadPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/{actorId}/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get media file by id (binary body from GridFS) */
        get: operations["v1MediaByIdGet"];
        put?: never;
        post?: never;
        /** Delete actor media file (GridFS) and remove references from actor */
        delete: operations["v1MediaByIdDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export full database snapshot (JSON)
         * @description Returns universities, actors, admins, and media files (Base64) in one document. Requires JWT.
         */
        get: operations["v1CatalogExportGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import full database snapshot (replaces all data)
         * @description Replaces all universities, actors, admins, and GridFS media with the payload.
         *     Format must be `format: "nsql1-catalog"` and compatible `version`.
         *     Response has no body on success.
         */
        post: operations["v1CatalogImportPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Admin login credentials */
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        /** @description Successful login — JWT for Authorization Bearer header */
        LoginResponse: {
            /** @description JWT */
            token?: string;
            /** @description Token lifetime in seconds */
            expiresIn?: number | null;
        };
        UniversityCreate: {
            /** @description University full name */
            name: string;
            /** @description Short name */
            shortName?: string | null;
            /** @description Former names */
            oldNames?: string[] | null;
        };
        /** @description MongoDB ObjectId (24 hex characters) */
        MongoId: string;
        UniversityCreateResponse: {
            /** @description University id when status=ok */
            id?: components["schemas"]["MongoId"];
            /** @enum {string} */
            status: "ok" | "failed";
            /** @description Error code when status=failed */
            errorCode?: string | null;
        };
        /** @description 401 response when JWT is missing or invalid */
        UnauthorizedError: {
            /** @example Unauthorized */
            error?: string;
            /** @description Reason (e.g. token required or token expired) */
            message?: string;
        };
        /** @description University search result row (id + names) */
        UniversitySearchItem: {
            id?: components["schemas"]["MongoId"];
            name?: string;
            shortName?: string | null;
            oldNames?: string[] | null;
        };
        /** @description Partial update: send at least one field. Empty string for shortName clears it; empty array for oldNames clears the list. */
        UniversityUpdate: {
            /** @description New full name */
            name?: string;
            /** @description Short name; empty string clears */
            shortName?: string | null;
            /** @description Replaces old names list entirely */
            oldNames?: string[] | null;
        };
        /**
         * @description Gender
         * @enum {string}
         */
        Gender: "male" | "female";
        /**
         * @description Title / rank
         * @enum {string}
         */
        Title: "honored" | "national" | "none";
        /** @description Contact link (social, personal site, etc.) */
        ContactLinkItem: {
            /** @description Label (e.g. VK, Rutube) */
            name?: string;
            /**
             * Format: uri
             * @description Link URL
             */
            url?: string;
        };
        /** @description University data (aggregated when returning an actor) */
        UniversityInfo: {
            name?: string;
            shortName?: string | null;
            oldNames?: string[] | null;
        };
        EducationItem: {
            /** @description University ObjectId */
            uniId?: components["schemas"]["MongoId"];
            graduationYear?: number | null;
            name?: string | null;
            /** @description University (filled when returning actor; no extra request needed) */
            readonly university?: components["schemas"]["UniversityInfo"];
        };
        FilmPlayItem: {
            title?: string;
            year?: number | null;
            role?: string | null;
            director?: string | null;
        };
        /** @description Theatre entry — name, years, plays */
        TheatrePlayItem: {
            /** @description Theatre name */
            name?: string;
            /** @description Years (e.g. 2010–2015) */
            years?: string | null;
            /** @description Plays */
            plays?: components["schemas"]["FilmPlayItem"][];
        };
        PhotoItem: {
            readonly id?: components["schemas"]["MongoId"];
            caption?: string | null;
        };
        VideoItem: {
            readonly id?: components["schemas"]["MongoId"];
            caption?: string | null;
        };
        Actor: {
            readonly id?: components["schemas"]["MongoId"];
            firstName?: string;
            lastName?: string;
            middleName?: string | null;
            /** Format: date */
            birthDate?: string | null;
            height?: number | null;
            weight?: number | null;
            gender?: components["schemas"]["Gender"];
            hairColor?: string | null;
            eyeColor?: string | null;
            bio?: string | null;
            title?: components["schemas"]["Title"];
            /** @description Phone number */
            phone?: string | null;
            /**
             * Format: email
             * @description Email
             */
            email?: string | null;
            /** @description Contact links (social, site, etc.) */
            links?: components["schemas"]["ContactLinkItem"][] | null;
            education?: components["schemas"]["EducationItem"][];
            films?: components["schemas"]["FilmPlayItem"][];
            /** @description Theatres and plays (for clients) */
            theatrePlayItems?: components["schemas"]["TheatrePlayItem"][];
            photos?: components["schemas"]["PhotoItem"][];
            /** @description ObjectId of main photo media (set on actor update, not on create) */
            readonly mainPhotoId?: components["schemas"]["MongoId"];
            videos?: components["schemas"]["VideoItem"][];
            genres?: string[];
            /** Format: date-time */
            readonly createdAt?: string | null;
            /** Format: date-time */
            readonly updatedAt?: string | null;
        };
        /** @description Paged actor list and total row count matching filters (ignoring limit/offset) */
        ActorListResponse: {
            /**
             * Format: int64
             * @description Total actors matching filters (full set, not only current page)
             */
            total: number;
            /** @description Page slice; empty when includeItems=false */
            actors: components["schemas"]["Actor"][];
        };
        /** @description On create only university id is sent; name and year are resolved from the catalog in responses. */
        EducationCreateItem: {
            /** @description University id from the university catalog */
            uniId: components["schemas"]["MongoId"];
        };
        ActorCreate: {
            firstName: string;
            lastName: string;
            middleName?: string | null;
            /** Format: date */
            birthDate?: string | null;
            height?: number | null;
            weight?: number | null;
            gender?: components["schemas"]["Gender"];
            hairColor?: string | null;
            eyeColor?: string | null;
            bio?: string | null;
            title?: components["schemas"]["Title"];
            /** @description Phone number */
            phone?: string | null;
            /**
             * Format: email
             * @description Email
             */
            email?: string | null;
            /** @description Contact links (social, site, etc.) */
            links?: components["schemas"]["ContactLinkItem"][] | null;
            /** @description University id per entry only; other fields are read from the catalog when loading an actor */
            education?: components["schemas"]["EducationCreateItem"][] | null;
            films?: components["schemas"]["FilmPlayItem"][];
            theatrePlayItems?: components["schemas"]["TheatrePlayItem"][];
            genres?: string[];
        };
        ActorCreateResponse: {
            /** @description Actor id when status=ok */
            id?: components["schemas"]["MongoId"];
            /** @enum {string} */
            status: "ok" | "failed";
            /** @description Error code when status=failed */
            errorCode?: string | null;
        };
        /**
         * @description Partial update (PATCH): send at least one field. Omitted fields keep previous values.
         *     List fields (links, education, films, theatrePlayItems, genres) replace the entire list when provided (use [] to clear).
         *     mainPhotoId must be one of the actor's photo ids from photos[].id; omit to leave unchanged.
         */
        ActorUpdate: {
            firstName?: string;
            lastName?: string;
            middleName?: string | null;
            /** Format: date */
            birthDate?: string | null;
            height?: number | null;
            weight?: number | null;
            gender?: components["schemas"]["Gender"];
            hairColor?: string | null;
            eyeColor?: string | null;
            bio?: string | null;
            title?: components["schemas"]["Title"];
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            links?: components["schemas"]["ContactLinkItem"][] | null;
            education?: components["schemas"]["EducationItem"][] | null;
            films?: components["schemas"]["FilmPlayItem"][] | null;
            theatrePlayItems?: components["schemas"]["TheatrePlayItem"][] | null;
            genres?: string[] | null;
            /** @description Must match an existing photos[].id; send null in JSON only if your client distinguishes omit vs null (otherwise omit) */
            mainPhotoId?: components["schemas"]["MongoId"];
        };
        /**
         * @description Media type on upload
         * @enum {string}
         */
        ActorMediaType: "photo" | "video";
        MediaUploadResponse: {
            mediaId?: components["schemas"]["MongoId"];
            /** @enum {string} */
            status: "ok" | "failed";
            /** @description Error code when status=failed (e.g. ACTOR_NOT_FOUND) */
            errorCode?: string | null;
        };
        /** @description Admin user as stored and exported in catalog (includes password hash) */
        AdminDocument: {
            id?: components["schemas"]["MongoId"];
            /** Format: email */
            email?: string;
            passwordHash?: string;
            /** Format: date-time */
            createdAt?: string | null;
        };
        /** @description GridFS file embedded in catalog export (payload as Base64) */
        CatalogMediaEntry: {
            /** @description Media ObjectId */
            id: string;
            actorId: string;
            filename: string;
            contentType?: string | null;
            /** @description photo or video */
            type: string;
            caption?: string | null;
            /** @description File bytes encoded as Base64 */
            dataBase64: string;
        };
        /** @description Full database snapshot for export/import; import replaces all universities, actors, admins, and GridFS media */
        CatalogSnapshot: {
            /** @example nsql1-catalog */
            format: string;
            /** @example 1 */
            version: number;
            /** @description Stored university documents (same shape as search rows) */
            universities: components["schemas"]["UniversitySearchItem"][];
            actors: components["schemas"]["Actor"][];
            admins: components["schemas"]["AdminDocument"][];
            media: components["schemas"]["CatalogMediaEntry"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1AuthLoginPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description JWT for Authorization Bearer header (mutating operations only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1UniversityCreatePost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniversityCreate"];
            };
        };
        responses: {
            /** @description Create result (id + status ok/failed + errorCode) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityCreateResponse"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    v1UniversitiesSearchGet: {
        parameters: {
            query: {
                /** @description Search string (name, shortName, oldNames) */
                q: string;
                /** @description Max number of results */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching universities (id, name, shortName, oldNames) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversitySearchItem"][];
                };
            };
        };
    };
    v1UniversityByIdDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description University id */
                id: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description University deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description University not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description University is still referenced by at least one actor (education.uniId) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1UniversityByIdPatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description University id */
                id: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniversityUpdate"];
            };
        };
        responses: {
            /** @description Update result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityCreateResponse"];
                };
            };
            /** @description No fields to update or invalid body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description University not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1ActorsGet: {
        parameters: {
            query?: {
                gender?: components["schemas"]["Gender"];
                /** @description Minimum age (years) */
                ageFrom?: number;
                /** @description Maximum age (years) */
                ageTo?: number;
                weightMin?: number;
                weightMax?: number;
                /** @description Minimum height (cm) */
                heightMin?: number;
                /** @description Maximum height (cm) */
                heightMax?: number;
                /** @description Activity year from */
                activityYearFrom?: number;
                activityYearTo?: number;
                /** @description University id */
                universityId?: components["schemas"]["MongoId"];
                theatre?: string;
                title?: components["schemas"]["Title"];
                hairColor?: string;
                eyeColor?: string;
                genres?: string[];
                /** @description Substring match on full name (firstName, lastName, middleName), case-insensitive */
                name?: string;
                limit?: number;
                offset?: number;
                /** @description If false, actors is empty but total is still computed for the same filters (avoids loading the page of items). */
                includeItems?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actors page and total count matching filters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorListResponse"];
                };
            };
        };
    };
    v1ActorCreatePost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorCreate"];
            };
        };
        responses: {
            /** @description Create result (id + status ok/failed + errorCode) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorCreateResponse"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    v1ActorByIdGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1ActorByIdDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actor deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Actor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1ActorByIdPatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorUpdate"];
            };
        };
        responses: {
            /** @description Updated actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"];
                };
            };
            /** @description No fields to update, invalid university id, or invalid mainPhotoId */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Actor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1ActorMediaUploadPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Actor id */
                id: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    type: components["schemas"]["ActorMediaType"];
                    caption?: string | null;
                };
            };
        };
        responses: {
            /** @description Upload result (mediaId + status ok/failed + errorCode) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Actor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1MediaByIdGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actorId: components["schemas"]["MongoId"];
                /** @description Media id from photos or videos list */
                mediaId: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File (image/* or video/*) */
            200: {
                headers: {
                    /**
                     * @description Browser HTTP cache: max-age in seconds.
                     *     Configured on the server as app.http.cache-control.media-max-age-seconds or MEDIA_CACHE_MAX_AGE_SECONDS (default 300).
                     *     If set to 0 in config, the header is omitted.
                     */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "video/*": string;
                    "application/octet-stream": string;
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1MediaByIdDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actorId: components["schemas"]["MongoId"];
                mediaId: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Actor or media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1CatalogExportGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSnapshot"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    v1CatalogImportPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogSnapshot"];
            };
        };
        responses: {
            /** @description Import completed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
}
