/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход (получить JWT) */
        post: operations["v1AuthLoginPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать вуз */
        post: operations["v1UniversityCreatePost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск вузов */
        get: operations["v1UniversitiesSearchGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить актёров по фильтрам */
        get: operations["v1ActorsGet"];
        put?: never;
        /** Создать актёра */
        post: operations["v1ActorCreatePost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить актёра по ID */
        get: operations["v1ActorByIdGet"];
        put?: never;
        post?: never;
        /** Удалить страницу актёра */
        delete: operations["v1ActorByIdDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить медиа актёра (фото или видео в GridFS) */
        post: operations["v1ActorMediaUploadPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/{actorId}/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить медиафайл по id (бинарный контент из GridFS) */
        get: operations["v1MediaByIdGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Учётные данные для входа (админ) */
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        /** @description Успешный логин — JWT для заголовка Authorization Bearer */
        LoginResponse: {
            /** @description JWT */
            token?: string;
            /** @description Срок жизни токена в секундах */
            expiresIn?: number | null;
        };
        UniversityCreate: {
            /** @description Название вуза */
            name: string;
            /** @description Короткое название */
            shortName?: string | null;
            /** @description Старые названия */
            oldNames?: string[] | null;
        };
        /** @description ID для поиска в MongoDB (ObjectId, 24 hex-символа) */
        MongoId: string;
        UniversityCreateResponse: {
            /** @description ID вуза при status=ok */
            id?: components["schemas"]["MongoId"];
            /** @enum {string} */
            status: "ok" | "failed";
            errorCode?: string | null;
        };
        /** @description Ответ 401 при отсутствии или невалидном JWT */
        UnauthorizedError: {
            /** @example Unauthorized */
            error?: string;
            /** @description Описание причины (например, требуется токен или токен истёк) */
            message?: string;
        };
        /** @description Элемент результата поиска вузов (id + название и варианты) */
        UniversitySearchItem: {
            id?: components["schemas"]["MongoId"];
            name?: string;
            shortName?: string | null;
            oldNames?: string[] | null;
        };
        /**
         * @description Пол
         * @enum {string}
         */
        Gender: "male" | "female";
        /**
         * @description Звание
         * @enum {string}
         */
        Title: "honored" | "national" | "none";
        /** @description Ссылка контакта (ВК, Макс, Рутуб, личный сайт и т.п.) */
        ContactLinkItem: {
            /** @description Название (например ВК, Макс, Рутуб) */
            name?: string;
            /**
             * Format: uri
             * @description URL ссылки
             */
            url?: string;
        };
        /** @description Данные вуза (агрегация при отдаче актёра) */
        UniversityInfo: {
            name?: string;
            shortName?: string | null;
            oldNames?: string[] | null;
        };
        EducationItem: {
            /** @description ObjectId вуза */
            uniId?: components["schemas"]["MongoId"];
            graduationYear?: number | null;
            name?: string | null;
            /** @description Вуз (заполняется при отдаче актёра, фронту не ходить отдельно) */
            readonly university?: components["schemas"]["UniversityInfo"];
        };
        FilmPlayItem: {
            title?: string;
            year?: number | null;
            role?: string | null;
            director?: string | null;
        };
        /** @description Элемент списка — театр и его пьесы (название, годы, пьесы) */
        TheatrePlayItem: {
            /** @description Название театра */
            name?: string;
            /** @description Годы (например 2010–2015) */
            years?: string | null;
            /** @description Пьесы */
            plays?: components["schemas"]["FilmPlayItem"][];
        };
        PhotoItem: {
            readonly id?: components["schemas"]["MongoId"];
            caption?: string | null;
        };
        VideoItem: {
            readonly id?: components["schemas"]["MongoId"];
            caption?: string | null;
        };
        Actor: {
            readonly id?: components["schemas"]["MongoId"];
            firstName?: string;
            lastName?: string;
            middleName?: string | null;
            /** Format: date */
            birthDate?: string | null;
            height?: number | null;
            weight?: number | null;
            gender?: components["schemas"]["Gender"];
            hairColor?: string | null;
            eyeColor?: string | null;
            bio?: string | null;
            title?: components["schemas"]["Title"];
            /** @description Телефонный номер */
            phone?: string | null;
            /**
             * Format: email
             * @description Электронная почта
             */
            email?: string | null;
            /** @description Ссылки (ВК, Макс, Рутуб, личный сайт и т.п.) */
            links?: components["schemas"]["ContactLinkItem"][] | null;
            education?: components["schemas"]["EducationItem"][];
            films?: components["schemas"]["FilmPlayItem"][];
            /** @description Театры и пьесы (для фронта) */
            theatrePlayItems?: components["schemas"]["TheatrePlayItem"][];
            photos?: components["schemas"]["PhotoItem"][];
            videos?: components["schemas"]["VideoItem"][];
            genres?: string[];
            /** Format: date-time */
            readonly createdAt?: string | null;
            /** Format: date-time */
            readonly updatedAt?: string | null;
        };
        ActorCreate: {
            firstName: string;
            lastName: string;
            middleName?: string | null;
            /** Format: date */
            birthDate?: string | null;
            height?: number | null;
            weight?: number | null;
            gender?: components["schemas"]["Gender"];
            hairColor?: string | null;
            eyeColor?: string | null;
            bio?: string | null;
            title?: components["schemas"]["Title"];
            /** @description Телефонный номер */
            phone?: string | null;
            /**
             * Format: email
             * @description Электронная почта
             */
            email?: string | null;
            /** @description Ссылки (ВК, Макс, Рутуб, личный сайт и т.п.) */
            links?: components["schemas"]["ContactLinkItem"][] | null;
            education?: components["schemas"]["EducationItem"][];
            films?: components["schemas"]["FilmPlayItem"][];
            theatrePlayItems?: components["schemas"]["TheatrePlayItem"][];
            genres?: string[];
        };
        ActorCreateResponse: {
            /** @description ID актёра при status=ok */
            id?: components["schemas"]["MongoId"];
            /** @enum {string} */
            status: "ok" | "failed";
            /** @description Код ошибки при status=failed */
            errorCode?: string | null;
        };
        /**
         * @description Тип медиа при загрузке
         * @enum {string}
         */
        ActorMediaType: "photo" | "video";
        MediaUploadResponse: {
            mediaId?: components["schemas"]["MongoId"];
            /** @enum {string} */
            status: "ok" | "failed";
            errorCode?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1AuthLoginPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description JWT для заголовка Authorization Bearer (только для операций изменения данных) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Неверный email или пароль */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1UniversityCreatePost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniversityCreate"];
            };
        };
        responses: {
            /** @description Результат создания (id + status ok/failed + errorCode) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityCreateResponse"];
                };
            };
            /** @description Нет или невалидный JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    v1UniversitiesSearchGet: {
        parameters: {
            query: {
                /** @description Строка поиска (по name, shortName, oldNames) */
                q: string;
                /** @description Максимум результатов */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список подходящих вузов (id, name, shortName, oldNames) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversitySearchItem"][];
                };
            };
        };
    };
    v1ActorsGet: {
        parameters: {
            query?: {
                gender?: components["schemas"]["Gender"];
                /** @description Возраст от (лет) */
                ageFrom?: number;
                ageTo?: number;
                weightMin?: number;
                weightMax?: number;
                /** @description Рост от (см) */
                heightMin?: number;
                /** @description Рост до (см) */
                heightMax?: number;
                /** @description Годы активности от */
                activityYearFrom?: number;
                activityYearTo?: number;
                /** @description ID вуза */
                universityId?: components["schemas"]["MongoId"];
                theatre?: string;
                title?: components["schemas"]["Title"];
                hairColor?: string;
                eyeColor?: string;
                genres?: string[];
                /** @description Подстрока по ФИО (firstName, lastName, middleName), без учёта регистра */
                name?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список актёров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"][];
                };
            };
        };
    };
    v1ActorCreatePost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorCreate"];
            };
        };
        responses: {
            /** @description Результат создания (id + status ok/failed + errorCode) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorCreateResponse"];
                };
            };
            /** @description Нет или невалидный JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    v1ActorByIdGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Актёр */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"];
                };
            };
            /** @description Не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1ActorByIdDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Актёр удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет или невалидный JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Актёр не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1ActorMediaUploadPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID актёра */
                id: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    type: components["schemas"]["ActorMediaType"];
                    caption?: string | null;
                };
            };
        };
        responses: {
            /** @description Результат загрузки (mediaId + status ok/failed + errorCode) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadResponse"];
                };
            };
            /** @description Ошибка запроса */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет или невалидный JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Актёр не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1MediaByIdGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actorId: components["schemas"]["MongoId"];
                /** @description ID элемента в photos или videos */
                mediaId: components["schemas"]["MongoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл (image/* или video/*) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "video/*": string;
                    "application/octet-stream": string;
                };
            };
            /** @description Медиа не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
